name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.PROJECT_ACCESS_TOKEN }}
        TARGET_REPO: eiaouan/y-animation
        TARGET_BRANCH: master
        BUILD_SCRIPT: pnpm build:docs
        BUILD_DIR: /packages/docs/docs/.vuepress/dist
        # CNAME: https://www.xxx.com